[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
bitflags = "0.9"
libc = "0.2"

[dependencies.atk-sys]
path = "../atk-sys"
version = "0.4.0"

[dependencies.cairo-sys-rs]
git = "https://github.com/gtk-rs/cairo"
version = "0.4.0"

[dependencies.gdk-pixbuf-sys]
path = "../gdk-pixbuf-sys"
version = "0.4.0"

[dependencies.gdk-sys]
path = "../gdk-sys"
version = "0.4.0"

[dependencies.gio-sys]
path = "../gio-sys"
version = "0.4.0"

[dependencies.glib-sys]
path = "../glib-sys"
version = "0.4.0"

[dependencies.gobject-sys]
path = "../gobject-sys"
version = "0.4.0"

[dependencies.pango-sys]
path = "../pango-sys"
version = "0.4.0"

[features]
v3_10 = ["v3_8"]
v3_12 = ["v3_10"]
v3_14 = ["v3_12"]
v3_16 = ["v3_14"]
v3_18 = ["v3_16"]
v3_20 = ["v3_18"]
v3_22 = ["v3_20"]
v3_22_6 = ["v3_22"]
v3_6 = []
v3_8 = ["v3_6"]

[lib]
name = "gtk_sys"

[package]
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
description = "FFI bindings to libgtk-3"
homepage = "http://gtk-rs.org/"
keywords = ["gtk", "ffi", "gtk-rs", "gnome"]
license = "MIT"
links = "gtk"
name = "gtk-sys"
repository = "https://github.com/gtk-rs/sys"
version = "0.4.0"
