dist: xenial
language: rust
matrix:
  include:
    - os: linux
      rust: nightly
      env: GTK=3.14
    - os: linux
      rust: nightly
      env: GTK=3.24 FEATURES=v2_32
    - os: linux
      rust: beta
      env: GTK=3.14
    - os: linux
      rust: beta
      env: GTK=3.24 FEATURES=v2_32
    - os: linux
      rust: 1.31.0
      env: GTK=3.14
    - os: linux
      rust: 1.31.0
      env: GTK=3.24 FEATURES=v2_32
    - os: osx
      rust: nightly
      env: GTK=3.14
    # - os: osx
    #   rust: nightly
    #   env: GTK=3.24 FEATURES=v2_32
    - os: osx
      rust: beta
      env: GTK=3.14
    # - os: osx
    #   rust: beta
    #   env: GTK=3.24 FEATURES=v2_32
    - os: osx
      rust: stable
      env: GTK=3.14
    # - os: osx
    #   rust: stable
    #   env: GTK=3.24 FEATURES=v2_32
sudo: true
addons:
  apt:
    packages:
    - libgtk-3-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gtk+3 cairo atk; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig;
    fi
script:
  - rustc --version
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ] && [ "$GTK" == "3.4" ]; then
    make regen_check;
    fi
  - cargo doc --features "dox,embed-lgpl-docs"
  - cargo test --features "$FEATURES,embed-lgpl-docs"
  # catch any sneaked in lgpl docs
  - cargo build --features "$FEATURES,purge-lgpl-docs" --jobs 1
  - git diff -R --exit-code
  - rustc --version
  - mkdir .cargo
  - echo 'paths = ["."]' > .cargo/config
  - git clone -q --depth 50 -b pending https://github.com/gtk-rs/examples _examples
  - cd _examples
  - ./build_travis.sh
