language: rust
rust:
  - nightly
  - beta
  - 1.28.0 # stable
env:
  - GTK=3.4
  - GTK=3.18
addons:
  apt:
    packages:
    - libgtk-3-dev
script:
  - rustc --version
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ] && [ "$GTK" == "3.4" ]; then
    make regen_check;
    fi
  - mkdir .cargo
  - echo 'paths = ["."]' > .cargo/config
  - git clone -q --depth 50 -b pending https://github.com/gtk-rs/examples _examples
  - cd _examples
  - ./build_travis.sh
