dist: xenial
language: rust
rust:
  - nightly
  - beta
  - 1.36.0
  - stable
env:
  - GTK=3.14
  - GTK=3.24
addons:
  apt:
    packages:
    - libgtk-3-dev
    - libmount-dev
script:
  - rustc --version
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ] && [ "$GTK" == "3.14" ]; then
    rustup component add rustfmt;
    make regen_check;
    fi
  - mkdir .cargo
  - echo 'paths = ["."]' > .cargo/config
  - git clone -q --depth 50 -b pending https://github.com/gtk-rs/examples _examples
  - cd _examples
  - ./build_travis.sh
