language: rust
matrix:
  include:
    - os: linux
      rust: nightly
      env: GTK=3.4
    - os: linux
      rust: nightly
      env: GTK=3.22.30
    - os: linux
      rust: beta
      env: GTK=3.4
    - os: linux
      rust: beta
      env: GTK=3.22.30
    - os: linux
      rust: stable
      env: GTK=3.4
    - os: linux
      rust: stable
      env: GTK=3.22.30
    - os: osx
      rust: nightly
      env: GTK=3.4
    # - os: osx
    #   rust: nightly
    #   env: GTK=3.22.30
    - os: osx
      rust: beta
      env: GTK=3.4
    # - os: osx
    #   rust: beta
    #   env: GTK=3.22.30
    - os: osx
      rust: stable
      env: GTK=3.4
    # - os: osx
    #   rust: stable
    #   env: GTK=3.22.30
sudo: true
addons:
  apt:
    packages:
    - libgtk-3-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gtk+3 cairo atk; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig; fi
script:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ] && [ "$GTK" == "3.4" ]; then
    make regen_check;
    fi
  - cargo doc --features "dox"
  - cargo test
  - rustc --version
  - mkdir .cargo
  - echo 'paths = ["."]' > .cargo/config
  - git clone -q --depth 50 -b pending https://github.com/rust-gnome/examples _examples
  - cd _examples
  - ./build_travis.sh
