[package]
name = "gdk"
version = "0.0.1"
authors = ["The Rust-GNOME Project Developers"]

description = "Rust bindings for the GDK library"
repository = "https://github.com/rust-gnome/gdk"
license = "MIT"
homepage = "https://github.com/rust-gnome/gdk"
documentation = "https://github.com/rust-gnome/gdk"

readme = "README.md"

keywords = ["gdk", "gtk", "gnome", "GUI"]

[lib]
name = "gdk"

[features]
default = ["gdk_3_6"]
gdk_3_4 = ["gdk-sys/gdk_3_4"]
gdk_3_6 = ["gdk-sys/gdk_3_6", "gdk_3_4"]
gdk_3_8 = ["gdk-sys/gdk_3_8", "gdk_3_6"]
gdk_3_10 = ["gdk-sys/gdk_3_10", "gdk_3_8"]
gdk_3_12 = ["gdk-sys/gdk_3_12", "gdk_3_10"]
gdk_3_14 = ["gdk-sys/gdk_3_14", "gdk_3_12"]

[dependencies]
libc = "0.1"
gdk-sys = "^0"
glib = "^0"
glib-sys = "^0"
