[package]
name = "gtk-rs-examples"
version = "0.0.1"
authors = ["The Gtk-rs Project Developers"]

[dependencies]
chrono = "0.4"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"

[dependencies.gio]
git = "https://github.com/gtk-rs/gio"

[dependencies.cairo-rs]
git = "https://github.com/gtk-rs/cairo"
features = ["png"]

[dependencies.pango]
git = "https://github.com/gtk-rs/pango"

[dependencies.gdk-pixbuf]
git = "https://github.com/gtk-rs/gdk-pixbuf"

[dependencies.gdk]
git = "https://github.com/gtk-rs/gdk"

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk"

[features]
#default = ["gtk_3_22"]
gtk_3_10 = ["gtk/v3_10"]
gtk_3_16 = ["gtk_3_10", "gtk/v3_16"]
gtk_3_18 = ["gtk_3_16", "gtk/v3_18"] #for CI tools
gtk_3_20 = ["gtk_3_18", "gtk/v3_20"] #for CI tools
gtk_3_22 = ["gtk_3_20", "gtk/v3_22"] #for CI tools
