[package]
name = "glib"
version = "0.1.2"
authors = ["The Gtk-rs Project Developers"]

description = "Rust bindings for the GLib library"
repository = "https://github.com/gtk-rs/glib"
license = "MIT"
homepage = "http://gtk-rs.org/"
documentation = "http://gtk-rs.org/docs/glib/"
keywords = ["glib", "gtk-rs", "gnome", "GUI"]

[lib]
name = "glib"

[dependencies]
bitflags = "0.5"
libc = "0.2"
glib-sys = "^0.3.3"
gobject-sys = "^0.3.3"

[features]
v2_38 = ["glib-sys/v2_38", "gobject-sys/v2_38"]
v2_40 = ["v2_38", "glib-sys/v2_40"]
v2_44 = ["v2_40", "glib-sys/v2_44", "gobject-sys/v2_44"]
v2_46 = ["v2_44", "glib-sys/v2_46", "gobject-sys/v2_46"]
v2_48 = ["v2_46", "glib-sys/v2_48"]
v2_50 = ["v2_48", "glib-sys/v2_50"]
