[package]
name = "pango"
version = "0.1.2"
authors = ["The Gtk-rs Project Developers"]

description = "Rust bindings for the Pango library"
repository = "https://github.com/gtk-rs/pango"
license = "MIT"
homepage = "http://gtk-rs.org/"
documentation = "http://gtk-rs.org/docs/pango/"

keywords = ["pango", "gtk-rs", "gnome"]

[features]
v1_31 = ["pango-sys/v1_31"]
v1_32 = ["v1_31", "pango-sys/v1_32"]
v1_32_4 = ["v1_32", "pango-sys/v1_32_4"]
v1_34 = ["v1_32_4", "pango-sys/v1_34"]
v1_36_7 = ["v1_34", "pango-sys/v1_36_7"]
v1_38 = ["v1_36_7", "pango-sys/v1_38"]
v1_42 = ["v1_38", "pango-sys/v1_42"]

[dependencies]
libc = "0.2"
bitflags = "0.5"
pango-sys = "^0.3.3"
glib = "^0.1.2"
