[package]
name = "cairo-rs"
version = "0.0.4"
authors = ["The RGtk Project Developers"]
build = "build.rs"

description = "Rust bindings for the Cairo library"
repository = "https://github.com/rgtk/cairo"
license = "MIT"
homepage = "https://github.com/rgtk/cairo"
documentation = "https://github.com/rgtk/cairo"

readme = "README.md"

keywords = ["cairo", "gtk", "gnome", "GUI"]

[lib]
name = "cairo"

[dependencies.cairo-sys-rs]
path = "./cairo-sys-rs"

[dependencies.glib]
git = "https://github.com/rgtk/glib"

[dependencies]
libc = "0.1"
c_vec = "~1.0"
