[package]
name = "pango"
documentation = "http://gtk-rs.org/docs/pango/"
homepage = "http://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
keywords = ["pango", "gtk-rs", "gnome"]
readme = "README.md"
version = "0.4.0"
description = "Rust bindings for the Pango library"
repository = "https://github.com/gtk-rs/pango"
license = "MIT"
exclude = [
    "gir-files/*",
]

[features]
v1_31 = ["pango-sys/v1_31"]
v1_32 = ["v1_31", "pango-sys/v1_32"]
v1_32_4 = ["v1_32", "pango-sys/v1_32_4"]
v1_34 = ["v1_32_4", "pango-sys/v1_34"]
v1_36_7 = ["v1_34", "pango-sys/v1_36_7"]
v1_38 = ["v1_36_7", "pango-sys/v1_38"]
v1_42 = ["v1_38", "pango-sys/v1_42"]
dox = ["pango-sys/dox", "glib/dox"]

[dependencies]
libc = "0.2"
bitflags = "1.0"
lazy_static = "1.0"

[dependencies.pango-sys]
version = "0.6.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.glib]
version = "0.5.0"
git = "https://github.com/gtk-rs/glib"

[dependencies.glib-sys]
version = "0.6.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gobject-sys]
version = "0.6.0"
git = "https://github.com/gtk-rs/sys"
