[package]
name = "gdk"
version = "0.5.2"
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"

description = "Rust bindings for the GDK 3 library"
repository = "https://github.com/gtk-rs/gdk"
license = "MIT"
homepage = "http://gtk-rs.org/"
documentation = "http://gtk-rs.org/docs/gdk/"

keywords = ["gdk", "gtk", "gtk-rs", "gnome", "GUI"]

[lib]
name = "gdk"

[features]
embed-lgpl-docs = ["gtk-rs-lgpl-docs", "cairo-rs/embed-lgpl-docs", "gdk-pixbuf/embed-lgpl-docs",
    "gio/embed-lgpl-docs"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs", "cairo-rs/purge-lgpl-docs", "gdk-pixbuf/purge-lgpl-docs",
    "gio/purge-lgpl-docs"]
v3_6 = ["gdk-sys/v3_6"]
v3_8 = ["v3_6", "gdk-sys/v3_8", "gdk-pixbuf/v2_28", "gio/v2_34", "pango/v1_32_4"]
v3_10 = ["v3_8", "gdk-sys/v3_10", "cairo-rs/v1_12", "gio/v2_36"]
v3_12 = ["v3_10", "gdk-sys/v3_12", "gio/v2_38"]
v3_14 = ["v3_12", "gdk-sys/v3_14", "gdk-pixbuf/v2_30", "gio/v2_40", "pango/v1_34"]
v3_16 = ["v3_14", "gdk-sys/v3_16", "gio/v2_42"]
v3_18 = ["v3_16", "gdk-sys/v3_18", "gio/v2_44"]
v3_20 = ["v3_18", "gdk-sys/v3_20", "gio/v2_48"]
v3_22 = ["v3_20", "gdk-sys/v3_22"]

[build-dependencies.gtk-rs-lgpl-docs]
version = "^0.1.1"
optional = true

[dependencies]
libc = "0.2"
bitflags = "0.5"
glib-sys = "^0.3.3"
gdk-sys = "^0.3.3"
cairo-rs = "^0.1.2"
gdk-pixbuf = "^0.1.2"
gio = "^0.1.2"
glib = "^0.1.2"
pango = "^0.1.2"
