[package]
name = "gtk-rs-examples"
version = "0.0.1"
authors = ["The Gtk-rs Project Developers"]

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"

[dependencies.cairo-rs]
git = "https://github.com/gtk-rs/cairo"

[dependencies.gdk-pixbuf]
git = "https://github.com/gtk-rs/gdk-pixbuf"

[dependencies.gdk]
git = "https://github.com/gtk-rs/gdk"

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk"

[features]
#default = ["gtk_3_20"]
gtk_3_10 = ["gtk/v3_10"]
gtk_3_16 = ["gtk_3_10", "gtk/v3_16"]
gtk_3_18 = ["gtk_3_16", "gtk/v3_18"] #for CI tools
gtk_3_20 = ["gtk_3_18", "gtk/v3_20"] #for CI tools

[[bin]]
name = "basic"

[[bin]]
name = "builder_basics"

[[bin]]
name = "cairotest"

[[bin]]
name = "cairo_threads"

[[bin]]
name = "grid"

[[bin]]
name = "gtktest"

[[bin]]
name = "notebook"

[[bin]]
name = "sync_widgets"

[[bin]]
name = "text_viewer"

[[bin]]
name = "treeview"

[[bin]]
name = "multithreading_context"

[[bin]]
name = "simple_treeview"

[[bin]]
name = "menu_bar"
