[package]
name = "gdk"
version = "0.0.1"
authors = ["The Rust-GNOME Project Developers"]

description = "Rust bindings for the GDK library"
repository = "https://github.com/rust-gnome/gdk"
license = "MIT"

[lib]
name = "gdk"

[features]
default = ["gdk_3_6"]
gdk_3_4 = ["gdk-sys/gdk_3_4"]
gdk_3_6 = ["gdk-sys/gdk_3_6", "gdk_3_4"]
gdk_3_8 = ["gdk-sys/gdk_3_8", "gdk_3_6"]
gdk_3_10 = ["gdk-sys/gdk_3_10", "gdk_3_8"]
gdk_3_12 = ["gdk-sys/gdk_3_12", "gdk_3_10"]
gdk_3_14 = ["gdk-sys/gdk_3_14", "gdk_3_12"]

[dependencies]
libc = "0.1"

[dependencies.gdk-sys]
path = "gdk-sys"
version = "0.1.0"

[dependencies.glib]
git = "https://github.com/rust-gnome/glib.git"

[dependencies.glib-sys]
git = "https://github.com/rust-gnome/glib.git"
