[package]
name = "gdk"
license = "MIT"
homepage = "http://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
keywords = ["gdk", "gtk", "gtk-rs", "gnome", "GUI"]
readme = "README.md"
documentation = "http://gtk-rs.org/docs/gdk/"
version = "0.11.0"
description = "Rust bindings for the GDK 3 library"
repository = "https://github.com/gtk-rs/gdk"
build = "build.rs"
exclude = [
    "gir-files/*",
]

[lib]
name = "gdk"

[features]
v3_16 = ["gdk-sys/v3_16"]
v3_18 = ["v3_16", "gdk-sys/v3_18"]
v3_20 = ["v3_18", "gdk-sys/v3_20"]
v3_22 = ["v3_20", "gdk-sys/v3_22"]
v3_24 = ["v3_22", "gdk-sys/v3_24"]
dox = ["gdk-sys/dox", "glib/dox", "gio/dox", "gdk-pixbuf/dox", "cairo-rs/dox", "pango/dox"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs", "cairo-rs/purge-lgpl-docs", "gdk-pixbuf/purge-lgpl-docs", "gio/purge-lgpl-docs"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs", "cairo-rs/embed-lgpl-docs", "gdk-pixbuf/embed-lgpl-docs", "gio/embed-lgpl-docs"]

["package.metadata.docs.rs"]
features = ["dox", "embed-lgpl-docs"]

[build-dependencies.gtk-rs-lgpl-docs]
version = "0.1.3"
optional = true
git = "https://github.com/gtk-rs/lgpl-docs"

[dependencies]
libc = "0.2"
bitflags = "1.0"
glib-sys = { git = "https://github.com/gtk-rs/sys" }
gdk-sys = { git = "https://github.com/gtk-rs/sys" }
gio-sys = { git = "https://github.com/gtk-rs/sys" }
gobject-sys = { git = "https://github.com/gtk-rs/sys" }
cairo-sys-rs = { git = "https://github.com/gtk-rs/cairo" }
cairo-rs = { git = "https://github.com/gtk-rs/cairo" }
gdk-pixbuf = { git = "https://github.com/gtk-rs/gdk-pixbuf" }
gio = { git = "https://github.com/gtk-rs/gio" }
glib = { git = "https://github.com/gtk-rs/glib" }
pango = { git = "https://github.com/gtk-rs/pango" }

[dev-dependencies]
gir-format-check = "^0.1"
