[package]
name = "gio"
version = "0.1.0"
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"

description = "Rust bindings for the GLib library"
repository = "https://github.com/gtk-rs/gio"
license = "MIT"
homepage = "http://gtk-rs.org/"
documentation = "http://gtk-rs.org/docs/gio/"
keywords = ["glib", "gio", "gtk-rs", "gnome"]

[lib]
name = "gio"

[features]
embed-lgpl-docs = ["gtk-rs-lgpl-docs"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs"]
v2_34 = ["gio-sys/v2_34"]
v2_36 = ["v2_34", "gio-sys/v2_36"]
v2_38 = ["v2_36", "gio-sys/v2_38"]
v2_40 = ["v2_38", "gio-sys/v2_40"]
v2_42 = ["v2_40", "gio-sys/v2_42"]
v2_44 = ["v2_42", "gio-sys/v2_44"]

[build-dependencies.gtk-rs-lgpl-docs]
git = "https://github.com/gtk-rs/lgpl-docs"
version = "0.1.0"
optional = true

[dependencies]
bitflags = "0.5"
libc = "0.2"

[dependencies.gio-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.1"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.1"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "0.1.0"

[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.1"
