[package]
name = "glib"
documentation = "http://gtk-rs.org/docs/glib/"
homepage = "http://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
description = "Rust bindings for the GLib library"
readme = "README.md"
version = "0.6.0"
keywords = ["glib", "gtk-rs", "gnome", "GUI"]
repository = "https://github.com/gtk-rs/glib"
license = "MIT"
exclude = [
    "gir-files/*",
]

[badges]
appveyor = { repository = "GuillaumeGomez/glib", service = "github" }
travis-ci = { repository = "gtk-rs/glib" }

[lib]
name = "glib"

[dependencies]
lazy_static = "1.2"
libc = "0.2"
bitflags = "1.0"
futures-preview = { version = "0.2", optional = true }
glib-sys = { git = "https://github.com/gtk-rs/sys", features = ["v2_40"] }
gobject-sys = { git = "https://github.com/gtk-rs/sys", features = ["v2_42"] }

[dev-dependencies]
tempfile = "3"

[features]
v2_44 = ["glib-sys/v2_44", "gobject-sys/v2_44"]
v2_46 = ["v2_44", "glib-sys/v2_46", "gobject-sys/v2_46"]
v2_48 = ["v2_46", "glib-sys/v2_48"]
v2_50 = ["v2_48", "glib-sys/v2_50"]
v2_52 = ["v2_50", "glib-sys/v2_52"]
v2_54 = ["v2_52", "glib-sys/v2_54", "gobject-sys/v2_54"]
v2_56 = ["v2_54", "glib-sys/v2_56"]
v2_58 = ["v2_56", "glib-sys/v2_58"]
futures = ["futures-preview"]
subclassing = []
dox = ["glib-sys/dox", "gobject-sys/dox"]
