[package]
name = "cairo"
version = "0.0.1"
authors = ["The Rust-gnome Project Developers"]

description = "Rust bindings for the Cairo library"
repository = "https://github.com/rust-gnome/cairo"
license = "MIT"

[lib]
name = "cairo"

[features]
default = ["cairo_1_10"]
cairo_1_10 = ["cairo-sys/cairo_1_10"]
cairo_1_12 = ["cairo-sys/cairo_1_12", "cairo_1_10"]

[dependencies]
libc = "0.1"
c_vec = "^1.0.0"

[dependencies.glib]
git = "https://github.com/rust-gnome/glib"

[dependencies.cairo-sys]
path = "cairo-sys"
version = "0.1.0"
