[package]
name = "gdk-pixbuf"
license = "MIT"
homepage = "http://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
keywords = ["gdk-pixbuf", "gtk-rs", "gnome"]
readme = "README.md"
documentation = "http://gtk-rs.org/docs/gdk_pixbuf/"
version = "0.3.0"
description = "Rust bindings for the GdkPixbuf library"
repository = "https://github.com/gtk-rs/gdk-pixbuf"
build = "build.rs"

[lib]
name = "gdk_pixbuf"

[features]
v2_28 = ["gdk-pixbuf-sys/v2_28"]
v2_30 = ["v2_28", "gdk-pixbuf-sys/v2_30"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs"]
v2_32 = ["v2_30", "gdk-pixbuf-sys/v2_32"]
v2_36 = ["v2_32", "gdk-pixbuf-sys/v2_36"]
dox = ["glib/dox", "gdk-pixbuf-sys/dox"]

[build-dependencies.gtk-rs-lgpl-docs]
version = "0.1.3"
optional = true
git = "https://github.com/gtk-rs/lgpl-docs"

[dependencies]
libc = "0.2"

[dependencies.gdk-pixbuf-sys]
version = "0.5.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.glib]
version = "0.4.0"
git = "https://github.com/gtk-rs/glib"

[dependencies.glib-sys]
version = "0.5.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gobject-sys]
version = "0.5.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gio-sys]
version = "0.5.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gio]
version = "0.3.0"
git = "https://github.com/gtk-rs/gio"
