[package]
name = "pangocairo"
documentation = "http://gtk-rs.org/docs/pangocairo/"
homepage = "http://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
keywords = ["pango", "cairo", "gtk-rs", "gnome"]
readme = "README.md"
version = "0.4.0"
description = "Rust bindings for the PangoCairo library"
repository = "https://github.com/gtk-rs/pangocairo"
license = "MIT"
build = "build.rs"
exclude = [
    "gir-files/*",
]

[features]
dox = ["glib/dox", "pango/dox", "cairo-rs/dox"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs", "cairo-rs/purge-lgpl-docs"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs", "cairo-rs/embed-lgpl-docs"]

[build-dependencies.gtk-rs-lgpl-docs]
version = "0.1.3"
optional = true
git = "https://github.com/gtk-rs/lgpl-docs"

[dependencies]
libc = "0.2"
bitflags = "0.9"

[dependencies.pango-sys]
version = "0.5.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.glib]
version = "0.4.0"
git = "https://github.com/gtk-rs/glib"

[dependencies.glib-sys]
version = "0.5.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gobject-sys]
version = "0.5.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.cairo-sys-rs]
version = "0.5.0"
git = "https://github.com/gtk-rs/cairo"

[dependencies.pangocairo-sys]
version = "0.6.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.pango]
version = "0.3.0"
git = "https://github.com/gtk-rs/pango"

[dependencies.cairo-rs]
version = "0.3.0"
git = "https://github.com/gtk-rs/cairo"
