[package]
name = "cairo-rs"
version = "0.1.3"
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"

description = "Rust bindings for the Cairo library"
repository = "https://github.com/gtk-rs/cairo"
license = "MIT"
homepage = "http://gtk-rs.org/"
documentation = "http://gtk-rs.org/docs/cairo/"

keywords = ["cairo", "gtk-rs", "gnome", "GUI"]

[lib]
name = "cairo"

[features]
embed-lgpl-docs = ["gtk-rs-lgpl-docs"]
png = ["cairo-sys-rs/png"]
xcb = ["cairo-sys-rs/xcb"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs"]
v1_12 = ["cairo-sys-rs/v1_12"]
default = ["glib"]

[build-dependencies.gtk-rs-lgpl-docs]
git = "https://github.com/gtk-rs/lgpl-docs"
version = "0.1.2"
optional = true

[dependencies.cairo-sys-rs]
path = "cairo-sys-rs"
version = "0.3.4"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "0.1.3"
optional = true

[dependencies]
libc = "0.2"
c_vec = "~1.2"

[target.'cfg(windows)'.dependencies]
winapi = "0.2.7"
