[package]
name = "gdk"
license = "MIT"
homepage = "http://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
keywords = ["gdk", "gtk", "gtk-rs", "gnome", "GUI"]
readme = "README.md"
documentation = "http://gtk-rs.org/docs/gdk/"
version = "0.9.0"
description = "Rust bindings for the GDK 3 library"
repository = "https://github.com/gtk-rs/gdk"
build = "build.rs"
exclude = [
    "gir-files/*",
]

[lib]
name = "gdk"

[features]
v3_6 = ["gdk-sys/v3_6"]
v3_8 = ["v3_6", "gdk-sys/v3_8", "gdk-pixbuf/v2_28", "gio/v2_34", "pango/v1_32_4"]
v3_10 = ["v3_8", "gdk-sys/v3_10", "cairo-rs/v1_12", "gio/v2_36"]
v3_12 = ["v3_10", "gdk-sys/v3_12", "gio/v2_38"]
v3_14 = ["v3_12", "gdk-sys/v3_14", "gdk-pixbuf/v2_30", "gio/v2_40", "pango/v1_34"]
v3_16 = ["v3_14", "gdk-sys/v3_16", "gio/v2_42"]
v3_18 = ["v3_16", "gdk-sys/v3_18", "gio/v2_44"]
v3_20 = ["v3_18", "gdk-sys/v3_20", "gio/v2_48"]
v3_22 = ["v3_20", "gdk-sys/v3_22"]
v3_22_30 = ["v3_22", "pango/v1_40", "gio/v2_54"]
v3_24 = ["v3_22_30", "pango/v1_42", "gio/v2_58"]
dox = ["gdk-sys/dox", "glib/dox", "gio/dox", "gdk-pixbuf/dox", "cairo-rs/dox", "pango/dox"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs", "cairo-rs/purge-lgpl-docs", "gdk-pixbuf/purge-lgpl-docs", "gio/purge-lgpl-docs"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs", "cairo-rs/embed-lgpl-docs", "gdk-pixbuf/embed-lgpl-docs", "gio/embed-lgpl-docs"]

[build-dependencies.gtk-rs-lgpl-docs]
version = "0.1.3"
optional = true
git = "https://github.com/gtk-rs/lgpl-docs"

[dependencies]
libc = "0.2"
bitflags = "1.0"
glib-sys = { git = "https://github.com/gtk-rs/sys" }
gdk-sys = { git = "https://github.com/gtk-rs/sys" }
gio-sys = { git = "https://github.com/gtk-rs/sys" }
gobject-sys = { git = "https://github.com/gtk-rs/sys" }
cairo-sys-rs = { git = "https://github.com/gtk-rs/cairo" }
cairo-rs = { git = "https://github.com/gtk-rs/cairo" }
gdk-pixbuf = { git = "https://github.com/gtk-rs/gdk-pixbuf" }
gio = { git = "https://github.com/gtk-rs/gio" }
glib = { git = "https://github.com/gtk-rs/glib" }
pango = { git = "https://github.com/gtk-rs/pango" }

[dev-dependencies]
gir-format-check = "^0.1"
