[package]
name = "gdk-pixbuf"
version = "0.1.2"
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"

description = "Rust bindings for the GdkPixbuf library"
repository = "https://github.com/gtk-rs/gdk-pixbuf"
license = "MIT"
homepage = "http://gtk-rs.org/"
documentation = "http://gtk-rs.org/docs/gdk_pixbuf/"

keywords = ["gdk-pixbuf", "gtk-rs", "gnome"]

[lib]
name = "gdk_pixbuf"

[features]
embed-lgpl-docs = ["gtk-rs-lgpl-docs"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs"]
v2_28 = ["gdk-pixbuf-sys/v2_28"]
v2_30 = ["v2_28", "gdk-pixbuf-sys/v2_30"]
v2_32 = ["v2_30", "gdk-pixbuf-sys/v2_32"]
v2_36 = ["v2_32", "gdk-pixbuf-sys/v2_36"]

[build-dependencies.gtk-rs-lgpl-docs]
version = "^0.1.1"
optional = true

[dependencies]
libc = "0.2"
gdk-pixbuf-sys = "^0.3.3"
glib = "^0.1.2"
