[package]
name = "glib"
version = "0.1.0"
authors = ["The Gtk-rs Project Developers"]

description = "Rust bindings for the GLib library"
repository = "https://github.com/gtk-rs/glib"
license = "MIT"
homepage = "http://gtk-rs.org/"
documentation = "http://gtk-rs.org/docs/glib/"
keywords = ["glib", "gtk-rs", "gnome", "GUI"]

[lib]
name = "glib"

[dependencies]
libc = "0.2"

[dependencies.gio-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.1"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.1"

[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.1"
