[build-dependencies]
system-deps = "3"

[dependencies]
libc = "0.2"

[dependencies.cairo-sys-rs]
path = "../../cairo/sys"

[dependencies.glib-sys]
path = "../../glib/sys"

[dependencies.pango-sys]
path = "../../pango/sys"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
dox = []

[lib]
name = "pango_cairo_sys"

[package]
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
description = "FFI bindings to libgtk-3"
homepage = "http://gtk-rs.org/"
keywords = ["gtk", "ffi", "gtk-rs", "gnome"]
license = "MIT"
links = "pangocairo-1.0"
name = "pangocairo-sys"
repository = "https://github.com/gtk-rs/gtk-rs"
version = "0.13.0"
edition = "2018"
[package.metadata.docs.rs]
features = ["dox"]
[package.metadata.system-deps.pangocairo]
name = "pangocairo"
version = "1.36"
