[package]
name = "pango-sys"
version = "0.1.2"
authors = ["The Rust-GNOME Project Developers"]
build = "build.rs"
links = "pango"

description = "FFI bindings to Pango"
repository = "https://github.com/rust-gnome/pango"
license = "MIT"
documentation = "https://github.com/rust-gnome/pango"
homepage = "https://github.com/rust-gnome/pango"

keywords = ["pango", "ffi", "gtk", "gnome"]

[dependencies.glib-sys]
git = "https://github.com/rust-gnome/glib"

[dependencies]
libc = "0.1"

[build-dependencies]
pkg-config = "0.3"