[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
libc = "0.2"
bitflags = "0.9"

[dependencies.glib-sys]
version = "0.4.0"
path = "../glib-sys"

[dependencies.gobject-sys]
version = "0.4.0"
path = "../gobject-sys"

[features]
v1_42 = ["v1_38"]
v1_38 = ["v1_36_7"]
v1_32 = ["v1_31"]
v1_32_4 = ["v1_32"]
v1_36_7 = ["v1_34"]
v1_34 = ["v1_32_4"]
v1_31 = []

[lib]
name = "pango_sys"

[package]
name = "pango-sys"
license = "MIT"
homepage = "http://gtk-rs.org/"
links = "pango"
authors = ["The Gtk-rs Project Developers"]
description = "FFI bindings to libpango-1.0"
version = "0.4.0"
keywords = ["pango", "ffi", "gtk-rs", "gnome"]
repository = "https://github.com/gtk-rs/sys"
build = "build.rs"