[build-dependencies]
system-deps = "3"

[dependencies]
libc = "0.2"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
v2_44 = []
v2_46 = ["v2_44"]
v2_48 = ["v2_46"]
v2_50 = ["v2_48"]
v2_52 = ["v2_50"]
v2_54 = ["v2_52"]
v2_56 = ["v2_54"]
v2_58 = ["v2_56"]
v2_60 = ["v2_58"]
v2_62 = ["v2_60"]
v2_64 = ["v2_62"]
dox = []
v2_66 = ["v2_64"]
v2_68 = ["v2_66"]

[lib]
name = "glib_sys"

[package]
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
description = "FFI bindings to libglib-2.0"
homepage = "http://gtk-rs.org/"
keywords = ["glib", "ffi", "gtk-rs", "gnome"]
license = "MIT"
links = "glib-2.0"
name = "glib-sys"
repository = "https://github.com/gtk-rs/gtk-rs"
version = "0.13.0"
edition = "2018"
[package.metadata.docs.rs]
features = ["dox"]
[package.metadata.system-deps.glib_2_0]
name = "glib-2.0"
version = "2.42"

[package.metadata.system-deps.glib_2_0.v2_44]
version = "2.44"

[package.metadata.system-deps.glib_2_0.v2_46]
version = "2.46"

[package.metadata.system-deps.glib_2_0.v2_48]
version = "2.48"

[package.metadata.system-deps.glib_2_0.v2_50]
version = "2.50"

[package.metadata.system-deps.glib_2_0.v2_52]
version = "2.52"

[package.metadata.system-deps.glib_2_0.v2_54]
version = "2.54"

[package.metadata.system-deps.glib_2_0.v2_56]
version = "2.56"

[package.metadata.system-deps.glib_2_0.v2_58]
version = "2.58"

[package.metadata.system-deps.glib_2_0.v2_60]
version = "2.60"

[package.metadata.system-deps.glib_2_0.v2_62]
version = "2.62"

[package.metadata.system-deps.glib_2_0.v2_64]
version = "2.64"

[package.metadata.system-deps.glib_2_0.v2_66]
version = "2.66"

[package.metadata.system-deps.glib_2_0.v2_68]
version = "2.68"

[package.metadata.system-deps.gobject_2_0]
name = "gobject-2.0"
version = "2.42"

[package.metadata.system-deps.gobject_2_0.v2_44]
version = "2.44"

[package.metadata.system-deps.gobject_2_0.v2_46]
version = "2.46"

[package.metadata.system-deps.gobject_2_0.v2_54]
version = "2.54"

[package.metadata.system-deps.gobject_2_0.v2_58]
version = "2.58"

[package.metadata.system-deps.gobject_2_0.v2_62]
version = "2.62"
