[options]
work_mode = "sys"
library = "GLib"
version = "2.0"
min_cfg_version = "2.42"
single_version_file = "."
girs_directories = ["../../gir-files"]

ignore = [
    "GLib.ANALYZER_ANALYZING",
    "GLib.DIR_SEPARATOR",
    "GLib.DIR_SEPARATOR_S",
    "GLib.GINT16_FORMAT",
    "GLib.GINT16_MODIFIER",
    "GLib.GINT32_FORMAT",
    "GLib.GINT32_MODIFIER",
    "GLib.GINT64_FORMAT",
    "GLib.GINT64_MODIFIER",
    "GLib.GNUC_FUNCTION",
    "GLib.GNUC_PRETTY_FUNCTION",
    "GLib.GUINT16_FORMAT",
    "GLib.GUINT32_FORMAT",
    "GLib.GUINT64_FORMAT",
    "GLib.GUINT64_MODIFIER",
    "GLib.GINTPTR_FORMAT",
    "GLib.GINTPTR_MODIFIER",
    "GLib.GUINTPTR_FORMAT",
    "GLib.GUINTPTR_MODIFIER",
    "GLib.GSIZE_FORMAT",
    "GLib.GSIZE_MODIFIER",
    "GLib.GSSIZE_FORMAT",
    "GLib.GSSIZE_MODIFIER",
    "GLib.HAVE_GINT64",
    "GLib.HAVE_GNUC_VARARGS",
    "GLib.HAVE_GNUC_VISIBILITY",
    "GLib.HAVE_GROWING_STACK",
    "GLib.HAVE_ISO_VARARGS",
    "GLib.MAJOR_VERSION",
    "GLib.MAXINT8",
    "GLib.MAXINT16",
    "GLib.MAXINT32",
    "GLib.MAXINT64",
    "GLib.MAXUINT8",
    "GLib.MAXUINT16",
    "GLib.MAXUINT32",
    "GLib.MAXUINT64",
    "GLib.MICRO_VERSION",
    "GLib.MININT8",
    "GLib.MININT16",
    "GLib.MININT32",
    "GLib.MININT64",
    "GLib.MINOR_VERSION",
    "GLib.MODULE_SUFFIX",
    "GLib.PID_FORMAT",
    "GLib.POLLFD_FORMAT",
    "GLib.SEARCHPATH_SEPARATOR",
    "GLib.SEARCHPATH_SEPARATOR_S",
    "GLib.SIZEOF_LONG",
    "GLib.SIZEOF_SIZE_T",
    "GLib.SIZEOF_SSIZE_T",
    "GLib.SIZEOF_VOID_P",
    "GLib.VA_COPY_AS_ARRAY",
    "GLib.VERSION_MIN_REQUIRED",
]

[[object]]
name = "GLib.*"
status = "generate"
    [[object.function]]
    pattern = "filename_(to|from)_(uri|utf8)"
    is_windows_utf8 = true
    [[object.function]]
    pattern = "(g|s|uns)etenv"
    is_windows_utf8 = true
    [[object.function]]
    name = "file_test"
    is_windows_utf8 = true
    [[object.function]]
    name = "file_get_contents"
    is_windows_utf8 = true
    [[object.function]]
    name = "file_open_tmp"
    is_windows_utf8 = true
    [[object.function]]
    name = "mkstemp"
    is_windows_utf8 = true
    [[object.function]]
    name = "get_current_dir"
    is_windows_utf8 = true
    [[object.function]]
    pattern = "spawn_async.*"
    is_windows_utf8 = true
    [[object.function]]
    name = "spawn_sync"
    is_windows_utf8 = true
    [[object.function]]
    pattern = "spawn_command_line_.*"
    is_windows_utf8 = true
    [[object.function]]
    name = "get_user_name"
    is_windows_utf8 = true
    [[object.function]]
    name = "get_real_name"
    is_windows_utf8 = true
    [[object.function]]
    name = "get_home_dir"
    is_windows_utf8 = true
    [[object.function]]
    name = "get_tmp_dir"
    is_windows_utf8 = true
    [[object.function]]
    name = "find_program_in_path"
    is_windows_utf8 = true
    [[object.function]]
    name = "unix_get_passwd_entry"
    cfg_condition = "unix"

[[object]]
name = "GLib.Dir"
status = "generate"
    [[object.function]]
    name = "open"
    is_windows_utf8 = true
    [[object.function]]
    name = "read_name"
    is_windows_utf8 = true

[[object]]
name = "GLib.IOChannel"
status = "generate"
    [[object.function]]
    name = "new_file"
    is_windows_utf8 = true

[[object]]
name = "GLib.Pid"
status = "manual"

[[object]]
name = "GLib.PollFD"
status = "manual"

[[object]]
name = "GLib.OptionGroup"
status = "generate"
    [[object.function]]
    name = "get_type"
    version = "2.44"
