[package]
authors = ["The gtk-rs Project Developers"]
description = "FFI bindings to libgdk-3-wayland"
homepage = "https://gtk-rs.org/"
keywords = ["gdk", "ffi", "gtk-rs", "gnome"]
license = "MIT"
name = "gdkwayland-sys"
repository = "https://github.com/gtk-rs/gtk3-rs"
version = "0.18.0"
edition = "2021"
rust-version = "1.70"

[lib]
name = "gdk_wayland_sys"

[features]
v3_24 = ["gdk/v3_24"]
v3_24_22 = ["v3_24"]

[dependencies]
libc = "0.2"

[dependencies.glib]
package = "glib-sys"
git = "https://github.com/gtk-rs/gtk-rs-core"

[dependencies.gobject]
package = "gobject-sys"
git = "https://github.com/gtk-rs/gtk-rs-core"

[dependencies.gdk]
package = "gdk-sys"
path = "../../gdk/sys"

[build-dependencies]
pkg-config = "0.3.7"
system-deps = "6"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
