[package]
authors = ["The gtk-rs Project Developers"]
description = "FFI bindings to libgdk-3-wayland"
homepage = "http://gtk-rs.org/"
keywords = ["gdk", "ffi", "gtk-rs", "gnome"]
license = "MIT"
name = "gdkwayland-sys"
repository = "https://github.com/gtk-rs/gtk3-rs"
version = "0.15.3"
edition = "2021"
rust-version = "1.56"

[lib]
name = "gdk_wayland_sys"

[features]
v3_20 = ["gdk/v3_20"]
v3_22 = ["v3_20", "gdk/v3_22"]
v3_24 = ["v3_22", "gdk/v3_24"]
v3_24_22 = ["v3_24"]
dox = ["gdk/dox"]

[dependencies]
libc = "0.2"

[dependencies.glib]
package = "glib-sys"
version = "0.15.1"
git = "https://github.com/gtk-rs/gtk-rs-core"
branch = "0.15"

[dependencies.gobject]
package = "gobject-sys"
version = "0.15.1"
git = "https://github.com/gtk-rs/gtk-rs-core"
branch = "0.15"

[dependencies.gdk]
package = "gdk-sys"
path = "../../gdk/sys"
version = "0.15.1"

[build-dependencies]
pkg-config = "0.3.7"
system-deps = "6"

[package.metadata.docs.rs]
features = ["dox"]
