[options]
work_mode = "sys"
library = "Gtk"
version = "3.0"
min_cfg_version = "3.14"
single_version_file = "."
girs_directories = ["../../gir-files"]

external_libraries = [
    "GLib",
    "GObject",
    "Gio",
    "Atk",
    "GdkPixbuf",
    "Gdk",
    "Pango",
    "Cairo",
]

manual = [
    "xlib.Window",
]

ignore = [
    "Gtk.BINARY_AGE",
    "Gtk.INTERFACE_AGE",
    "Gtk.MAJOR_VERSION",
    "Gtk.MICRO_VERSION",
    "Gtk.MINOR_VERSION",
]

[[object]]
name = "Gtk.ButtonRole"
status = "generate"
version = "3.16"

[[object]]
name = "Gtk.FileChooserNative"
status = "generate"
version = "3.20"

[[object]]
name = "Gtk.ModelButton"
status = "generate"
version = "3.16"

[[object]]
name = "Gtk.NativeDialog"
status = "generate"
version = "3.20"

[[object]]
name = "Gtk.PopoverMenu"
status = "generate"
version = "3.16"

[[object]]
name = "Gtk.ShortcutsGroup"
status = "generate"
version = "3.20"

[[object]]
name = "Gtk.ShortcutsSection"
status = "generate"
version = "3.20"

[[object]]
name = "Gtk.ShortcutsShortcut"
status = "generate"
version = "3.20"

[[object]]
name = "Gtk.ShortcutsWindow"
status = "generate"
version = "3.20"

[[object]]
name = "Gtk.StyleContextPrintFlags"
status = "generate"
version = "3.20"

[[object]]
name = "Gtk.EventControllerKey"
status = "generate"
version = "3.24"

[[object]]
name = "Gtk.EventControllerMotion"
status = "generate"
version = "3.24"

[[object]]
name = "Gtk.EventControllerScroll"
status = "generate"
version = "3.24"

[[object]]
name = "Gtk.FontChooserLevel"
status = "generate"
version = "3.24"

[[object]]
name = "Gtk.GestureStyle"
status = "generate"
version = "3.24"

[[object]]
name = "Gtk.HeaderBarAccessible"
status = "generate"
version = "3.24.11"

[[object]]
name = "Gtk.PadActionType"
status = "generate"
version = "3.22"

[[object]]
name = "Gtk.PadController"
status = "generate"
version = "3.22"

[[object]]
name = "Gtk.ShortcutLabel"
status = "generate"
version = "3.22"

[[object]]
name = "Gtk.StackAccessible"
status = "generate"
version = "3.22"
