[build-dependencies]
system-deps = "3"

[dependencies]
libc = "0.2"

[dependencies.gio-sys]
path = "../../gio/sys"

[dependencies.glib-sys]
path = "../../glib/sys"

[dependencies.gobject-sys]
path = "../../glib/gobject-sys"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
v2_32 = []
v2_36 = ["v2_32"]
v2_36_8 = ["v2_36"]
v2_40 = ["v2_36_8"]
dox = []

[lib]
name = "gdk_pixbuf_sys"

[package]
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
description = "FFI bindings to libgdk_pixbuf-2.0"
homepage = "http://gtk-rs.org/"
keywords = ["gdk-pixbuf", "ffi", "gtk-rs", "gnome"]
license = "MIT"
links = "gdk_pixbuf-2.0"
name = "gdk-pixbuf-sys"
repository = "https://github.com/gtk-rs/gtk-rs"
version = "0.13.0"
edition = "2018"
[package.metadata.docs.rs]
features = ["dox"]
[package.metadata.system-deps.gdk_pixbuf_2_0]
name = "gdk-pixbuf-2.0"
version = "2.30"

[package.metadata.system-deps.gdk_pixbuf_2_0.v2_32]
version = "2.32"

[package.metadata.system-deps.gdk_pixbuf_2_0.v2_36]
version = "2.36"

[package.metadata.system-deps.gdk_pixbuf_2_0.v2_36_8]
version = "2.36.8"

[package.metadata.system-deps.gdk_pixbuf_2_0.v2_40]
version = "2.40"
