[options]
work_mode = "sys"
library = "GdkPixbuf"
version = "2.0"
min_cfg_version = "2.30"
single_version_file = "."
girs_directories = ["../../gir-files"]

external_libraries = [
    "GLib",
    "GObject",
    "Gio",
]

ignore = [
    "GdkPixbuf.PIXBUF_FEATURES_H",
    "GdkPixbuf.PIXBUF_MAJOR",
    "GdkPixbuf.PIXBUF_MICRO",
    "GdkPixbuf.PIXBUF_MINOR",
    "GdkPixbuf.PIXBUF_VERSION",
]

[[object]]
name = "GdkPixbuf.Pixbuf"
status = "generate"
    [[object.function]]
    pattern = "new_from_file.*"
    is_windows_utf8 = true
    [[object.function]]
    pattern = "savev?"
    is_windows_utf8 = true
    [[object.function]]
    name = "new_from_file"
    is_windows_utf8 = true

[[object]]
name = "GdkPixbuf.PixbufAnimation"
status = "generate"
    [[object.function]]
    name = "new_from_file"
    is_windows_utf8 = true
