[package]
name = "cairo-sys-rs"
version = "0.1.3"
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
links = "cairo"

description = "FFI bindings to Cairo"
repository = "https://github.com/rust-gnome/cairo"
license = "MIT"
homepage = "https://github.com/rust-gnome/cairo"
documentation = "https://github.com/rust-gnome/cairo"

keywords = ["cairo", "ffi", "gtk", "gnome"]

[lib]
name = "cairo_sys"

[dependencies]
libc = "0.1"

[build-dependencies]
pkg-config = "0.3.5"
