[options]
work_mode = "sys"
library = "GdkX11"
version = "3.0"
min_cfg_version = "3.0"
single_version_file = "."

external_libraries = [
   "Gdk",
   "GdkPixbuf",
   "Gio",
   "GLib",
   "GObject",
   "Pango"
]

ignore = [
]
