[options]
work_mode = "sys"
library = "Gtk"
version = "3.0"
min_cfg_version = "3.14"
single_version_file = "."

external_libraries = [
   "GLib",
   "GObject",
   "Gio",
   "Atk",
   "GdkPixbuf",
   "Gdk",
   "Pango",
   "Cairo",
]

manual = [
   "xlib.Window",
]

ignore = [
	"Gtk.BINARY_AGE",
	"Gtk.INTERFACE_AGE",
	"Gtk.MAJOR_VERSION",
	"Gtk.MICRO_VERSION",
	"Gtk.MINOR_VERSION",
]
