[options]
work_mode = "sys"
girs_dir = "gir-files"
library = "GdkPixbuf"
version = "2.0"
min_cfg_version = "2.26"
target_path = "gdk-pixbuf-sys"
external_libraries = [
   "GLib",
   "GObject",
   "Gio",
]
