[build-dependencies]
pkg-config = "0.3.7"
system-deps = "6"

[dependencies]
libc = "0.2"

[dependencies.cairo]
package = "cairo-sys-rs"
git = "https://github.com/gtk-rs/gtk-rs-core"

[dependencies.gdk_pixbuf]
package = "gdk-pixbuf-sys"
git = "https://github.com/gtk-rs/gtk-rs-core"

[dependencies.gio]
package = "gio-sys"
git = "https://github.com/gtk-rs/gtk-rs-core"

[dependencies.glib]
package = "glib-sys"
git = "https://github.com/gtk-rs/gtk-rs-core"

[dependencies.gobject]
package = "gobject-sys"
git = "https://github.com/gtk-rs/gtk-rs-core"

[dependencies.pango]
package = "pango-sys"
git = "https://github.com/gtk-rs/gtk-rs-core"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
v3_24 = []

[lib]
name = "gdk_sys"

[package]
authors = ["The gtk-rs Project Developers"]
build = "build.rs"
description = "FFI bindings to libgdk-3"
homepage = "https://gtk-rs.org/"
keywords = ["gdk", "ffi", "gtk-rs", "gnome"]
license = "MIT"
links = "gdk-3"
name = "gdk-sys"
repository = "https://github.com/gtk-rs/gtk3-rs"
version = "0.19.0"
edition = "2021"
rust-version = "1.70"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
features = []

[package.metadata.system-deps.gdk_3_0]
name = "gdk-3.0"
version = "3.22"

[package.metadata.system-deps.gdk_3_0.v3_24]
version = "3.24"
