[package]
name = "gdk-sys"
version = "0.1.1"
authors = ["The Rust-GNOME Project Developers"]
build = "build.rs"
links = "gdk"

description = "FFI bindings to GDK"
repository = "https://github.com/rust-gnome/gdk"
license = "MIT"
homepage = "https://github.com/rust-gnome/gdk"
documentation = "https://github.com/rust-gnome/gdk"

keywords = ["gdk", "ffi", "gtk", "gnome"]

[lib]
name = "gdk_sys"

[features]
gdk_3_4 = []
gdk_3_6 = ["gdk_3_4"]
gdk_3_8 = ["gdk_3_6"]
gdk_3_10 = ["gdk_3_8"]
gdk_3_12 = ["gdk_3_10"]
gdk_3_14 = ["gdk_3_12"]

[dependencies.glib-sys]
git  = "https://github.com/rust-gnome/glib"

[dependencies.cairo-sys-rs]
git = "https://github.com/rust-gnome/cairo"

[dependencies]
bitflags = "0.1"
libc = "0.1"

[build-dependencies]
pkg-config = "0.3"
