[package]
authors = ["The gtk-rs Project Developers"]
description = "FFI binding for libgdkx11"
homepage = "http://gtk-rs.org/"
keywords = ["gdkx11", "ffi", "gtk-rs", "gnome"]
license = "MIT"
repository = "https://github.com/gtk-rs/gtk3-rs"
name = "gdkx11-sys"
version = "0.14.0"
build = "build.rs"
edition = "2018"

[package.metadata.docs.rs]
features = ["dox"]

[package.metadata.system-deps.gdk_x11_3_0]
name = "gdk-x11-3.0"
version = "3.18"

[package.metadata.system-deps.gdk_x11_3_0.v3_24]
version = "3.24"

[package.metadata.system-deps.gdk_x11_3_0.v3_24_2]
version = "3.24.2"

[lib]
name = "gdk_x11_sys"

[dependencies]
libc = "0.2"
x11 = "2.18"

[dependencies.gdk-sys]
version = "0.14.0"

[dependencies.glib-sys]
version = "0.14.0"

[dependencies.cairo]
package = "cairo-sys-rs"
optional = true
version = "0.14.0"

[build-dependencies]
system-deps = "3"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
v3_22 = []
v3_24 = []
v3_24_2 = ["v3_24", "cairo"]
dox = ["cairo"]
