[build-dependencies]
system-deps = "3"

[dependencies]
libc = "0.2"

[dependencies.glib-sys]
path = "../../glib/sys"

[dependencies.gobject-sys]
path = "../../glib/gobject-sys"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
v1_36_7 = []
v1_38 = ["v1_36_7"]
v1_42 = ["v1_38"]
v1_44 = ["v1_42"]
dox = []
v1_46 = ["v1_44"]

[lib]
name = "pango_sys"

[package]
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
description = "FFI bindings to libpango-1.0"
homepage = "http://gtk-rs.org/"
keywords = ["pango", "ffi", "gtk-rs", "gnome"]
license = "MIT"
links = "pango-1.0"
name = "pango-sys"
repository = "https://github.com/gtk-rs/gtk-rs"
version = "0.13.0"
edition = "2018"
[package.metadata.docs.rs]
features = ["dox"]
[package.metadata.system-deps.pango]
name = "pango"
version = "1.36"

[package.metadata.system-deps.pango.v1_36_7]
version = "1.36.7"

[package.metadata.system-deps.pango.v1_38]
version = "1.38"

[package.metadata.system-deps.pango.v1_42]
version = "1.42"

[package.metadata.system-deps.pango.v1_44]
version = "1.44"

[package.metadata.system-deps.pango.v1_46]
version = "1.46"
