[options]
work_mode = "sys"
library = "Pango"
version = "1.0"
min_cfg_version = "1.36"
single_version_file = "."
girs_directories = ["../../gir-files"]

external_libraries = [
    "GLib",
    "GObject",
]

[[object]]
name = "Pango.Attribute"
status = "generate"
    [[object.function]]
    name = "get_type"
    version = "1.44"

[[object]]
name = "Pango.AttrIterator"
status = "generate"
    [[object.function]]
    name = "get_type"
    version = "1.44"

[[object]]
name = "Pango.Coverage"
status = "generate"
    [[object.function]]
    name = "get_type"
    version = "1.44"

[[object]]
name = "Pango.ScriptIter"
status = "generate"
    [[object.function]]
    name = "get_type"
    version = "1.44"

[[object]]
name = "Pango.ShapeFlags"
status = "generate"
    [[object.function]]
    name = "get_type"
    version = "1.44"

[[object]]
name = "Pango.ShowFlags"
status = "generate"
    [[object.function]]
    name = "get_type"
    version = "1.44"
