[build-dependencies]
system-deps = "3"

[dependencies]
libc = "0.2"

[dependencies.glib-sys]
path = "../sys"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
v2_44 = []
v2_46 = ["v2_44"]
v2_54 = ["v2_46"]
v2_58 = ["v2_54"]
v2_62 = ["v2_58"]
dox = []
v2_66 = ["v2_62"]

[lib]
name = "gobject_sys"

[package]
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
description = "FFI bindings to libgobject-2.0"
homepage = "http://gtk-rs.org/"
keywords = ["gobject", "ffi", "gtk-rs", "gnome"]
license = "MIT"
links = "gobject-2.0"
name = "gobject-sys"
repository = "https://github.com/gtk-rs/gtk-rs"
version = "0.13.0"
edition = "2018"
[package.metadata.docs.rs]
features = ["dox"]
[package.metadata.system-deps.gobject_2_0]
name = "gobject-2.0"
version = "2.42"

[package.metadata.system-deps.gobject_2_0.v2_44]
version = "2.44"

[package.metadata.system-deps.gobject_2_0.v2_46]
version = "2.46"

[package.metadata.system-deps.gobject_2_0.v2_54]
version = "2.54"

[package.metadata.system-deps.gobject_2_0.v2_58]
version = "2.58"

[package.metadata.system-deps.gobject_2_0.v2_62]
version = "2.62"

[package.metadata.system-deps.gobject_2_0.v2_66]
version = "2.66"
