[options]
work_mode = "sys"
library = "GObject"
version = "2.0"
min_cfg_version = "2.42"
single_version_file = "."
girs_directories = ["../../gir-files"]

external_libraries = [
    "GLib",
]

ignore = [
    "GObject.VaClosureMarshal",
    "GObject.SignalCVaMarshaller",
]
