on:
  push:
    branches: [master]
  pull_request:

name: docs

jobs:
  docs:
    runs-on: ubuntu-latest
    name: build
    container:
      image: ghcr.io/gtk-rs/gtk-rs/gtk:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - working-directory: gir
        run: cargo build --release
      - run: ./gir/target/release/gir -c ./atk/Gir.toml -d ./gir-files --doc-target-path docs.md -m doc
      - run: ./gir/target/release/gir -c ./gdk/Gir.toml -d ./gir-files --doc-target-path docs.md -m doc
      - run: ./gir/target/release/gir -c ./gdk-pixbuf/Gir.toml -d ./gir-files --doc-target-path docs.md -m doc
      - run: ./gir/target/release/gir -c ./gdkx11/Gir.toml -d ./gir-files --doc-target-path docs.md -m doc
      - run: ./gir/target/release/gir -c ./gio/Gir.toml -d ./gir-files --doc-target-path docs.md -m doc
      - run: ./gir/target/release/gir -c ./graphene/Gir.toml -d ./gir-files --doc-target-path docs.md -m doc
      - run: ./gir/target/release/gir -c ./gtk/Gir.toml -d ./gir-files --doc-target-path docs.md -m doc
      - run: ./gir/target/release/gir -c ./pango/Gir.toml -d ./gir-files --doc-target-path docs.md -m doc
      - run: ./gir/target/release/gir -c ./pangocairo/Gir.toml -d ./gir-files --doc-target-path docs.md -m doc
      - run: cargo install rustdoc-stripper
      - run: rustdoc-stripper -g -o ./atk/docs.md
      - run: rustdoc-stripper -g -o ./gdk/docs.md
      - run: rustdoc-stripper -g -o ./gdk-pixbuf/docs.md
      - run: rustdoc-stripper -g -o ./gdkx11/docs.md
      - run: rustdoc-stripper -g -o ./gio/docs.md
      - run: rustdoc-stripper -g -o ./graphene/docs.md
      - run: rustdoc-stripper -g -o ./gtk/docs.md
      - run: rustdoc-stripper -g -o ./pango/docs.md
      - run: rustdoc-stripper -g -o ./pangocairo/docs.md
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: -p atk -p atk-sys -p cairo-rs -p cairo-sys-rs -p gdk -p gdk-sys -p gdk-pixbuf -p gdk-pixbuf-sys -p gdkx11 -p gdkx11-sys -p gio -p gio-sys -p glib -p gobject-sys -p glib-sys -p glib-macros -p graphene-rs -p graphene-sys -p gtk -p gtk-sys -p pango -p pango-sys -p pangocairo -p pangocairo-sys --features "dox,embed-lgpl-docs" --no-deps
        env:
          RUSTDOCFLAGS: "--enable-index-page -Zunstable-options"

      - name: deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc/
